### ISSUE TITLE
Crash when normal use

### ISSUE THREAD

**Issue by flifloo** [ApexCobalt/Yiffdex#1]
Hi, I got a crash when I use Yiffdex GUI so I launch in nogui and there is the crash logs :

```
[43%] D:\Google Drive\Images\Furry\OwO\994572aa2e0ffeddb8c54a151d6e73f5.jpg - PASS.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\flifloo\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".\yiffdex.py", line 292, in run
    if self.force is False and is_marked(f):
  File ".\yiffdex.py", line 75, in is_marked
    exif = piexif.load(file)
  File "C:\Users\flifloo\AppData\Local\Programs\Python\Python36\lib\site-packages\piexif\_load.py", line 27, in load
    exifReader = _ExifReader(input_data)
  File "C:\Users\flifloo\AppData\Local\Programs\Python\Python36\lib\site-packages\piexif\_load.py", line 100, in __init__
    raise InvalidImageDataError("Given file is neither JPEG nor TIFF.")
piexif._exceptions.InvalidImageDataError: Given file is neither JPEG nor TIFF.

[43%] D:\Google Drive\Images\Furry\OwO\99482efdd1fc446cf6562d2ec9c2e1d1.jpg - Traceback (most recent call last):
  File ".\yiffdex.py", line 414, in <module>
    if yiffdex_app.inkbunny_api is not None:
AttributeError: 'Yiffdex' object has no attribute 'inkbunny_api'`
```

**Comment by ApexCobalt** [comment]
In this report, there are two errors, the first one :

```
Traceback (most recent call last):
  File "C:\Users\flifloo\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File ".\yiffdex.py", line 292, in run
    if self.force is False and is_marked(f):
  File ".\yiffdex.py", line 75, in is_marked
    exif = piexif.load(file)
  File "C:\Users\flifloo\AppData\Local\Programs\Python\Python36\lib\site-packages\piexif\_load.py", line 27, in load
    exifReader = _ExifReader(input_data)
  File "C:\Users\flifloo\AppData\Local\Programs\Python\Python36\lib\site-packages\piexif\_load.py", line 100, in __init__
    raise InvalidImageDataError("Given file is neither JPEG nor TIFF.")
piexif._exceptions.InvalidImageDataError: Given file is neither JPEG nor TIFF.
```

Its happen because it try to load the exif of the file but the file isn't a valid JPEG image. In this case, after observation it's a PNG file with .jpg extension. Because we only check the extension, to avoid crashing the program when the extension isn't matching with the type of file, I added two extra try / catch.


The second error is :

```
Traceback (most recent call last):
  File ".\yiffdex.py", line 414, in <module>
    if yiffdex_app.inkbunny_api is not None:
AttributeError: 'Yiffdex' object has no attribute 'inkbunny_api'`
```

Is just a code mistake, now corrected, the attribute is `inkbunny`  not `inkbunny_api`.

This bugs are fixed by the commit a0409fba385260db5a07cacc5f8338fe6cb0e855 .
